sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tLu2i425B8wFBSm927g
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: MrTSLtw5bNJuf3aHjd3CG79pr5jaIw
    bucket-name: skytakeout132